name: nizar_ztn_portfolio
description: "A new Flutter project."

publish_to: "none"

version: 2.0.3+23

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^16.2.4
  url_launcher: ^6.3.1
  firebase_core: ^4.1.1
  firebase_analytics_web: ^0.6.0+2
  firebase_analytics: ^12.0.2

  google_fonts: ^6.2.1
  gap: ^3.0.1
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.16
  responsive_grid_list: ^1.4.0
  universal_html: ^2.2.4
  typeset: ^2.1.1
  flutter_markdown: ^0.7.4+3
  intl: ^0.20.1
  webview_flutter_web: ^0.2.3+2
  webview_flutter: ^4.12.1
  flutter_html: ^3.0.0-beta.2
  font_awesome_flutter: ^10.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/mob/food_app/
    - assets/images/mob/ig/
    - assets/images/mob/live_stream_simulator/
    - assets/images/mob/jdm/
    - assets/images/mob/nx_shop/
    - assets/images/mob/peak_store/
    - assets/images/mob/quick_qr_pro/
    - assets/images/mob/sa3arli/
    - assets/images/mob/tiktok/
    - assets/images/mob/tune_hub/
    - assets/images/mob/audio_libro/
    - assets/images/mob/stretchyv1/
    - assets/images/mob/stretchyv2/
    - assets/images/mob/dupli/
    - assets/images/mob/social_profile_prank/
    - assets/images/mob/workout_finder/
    # - assets/images//
    - assets/icons/
    - assets/fonts/
    - assets/svgs/
    - assets/images/game_design/poly_town/
    - assets/images/game_design/blaster_pranks/
    - assets/images/game_design/medieval_pack/
    - assets/images/game_design/double_jump/

    - assets/mark_down/

  fonts:
    - family: Agustina
      fonts:
        - asset: assets/fonts/agustina/agustina.otf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/montserrat.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
